from building import *
import os

cwd = GetCurrentDir()
group = []

src = Glob('InfoNES_system.c')
src += Glob('rom.c')
src += Glob('InfoNES.cpp')
src += Glob('InfoNES_Mapper.cpp')
src += Glob('InfoNES_pAPU.cpp')
src += Glob('K6502.cpp')
src += Glob('rt_key_scan.c')


CPPPATH = [cwd]

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('NES', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
